apiVersion: batch/v1
kind: CronJob
metadata:
  name: iam-checker
spec:
  schedule: "* 10 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iam-checker
            image: dsdego/iam-checker:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: my-env
            command:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure
          automountServiceAccountToken: false

