apiVersion: v1
kind: Pod
metadata:
  name: iam-checker
spec:
  containers:
  - name: iam-checker
    image: dsdego/iam-checker:latest
    envFrom:
      - secretRef:
          name: my-env
    ports:
    - containerPort: 80
  restartPolicy: "Never"